-- MySQL Script generated by MySQL Workbench
-- Sat Oct 16 19:25:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbpousada
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbpousada
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbpousada` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbpousada` ;

-- -----------------------------------------------------
-- Table `dbpousada`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpousada`.`funcionario` (
  `id` INT NOT NULL,
  `Senha` INT NULL DEFAULT NULL,
  `Login` INT NULL DEFAULT NULL,
  `Nome` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbpousada`.`hospedagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpousada`.`hospedagem` (
  `Valor_total` DECIMAL(15,2) NULL DEFAULT NULL,
  `Status` VARCHAR(15) NULL DEFAULT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbpousada`.`tipohospede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpousada`.`tipohospede` (
  `id` INT NOT NULL,
  `Descricao` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbpousada`.`hospede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpousada`.`hospede` (
  `id` INT NOT NULL,
  `Endereco` VARCHAR(250) NULL DEFAULT NULL,
  `Nome` VARCHAR(250) NULL DEFAULT NULL,
  `Status` VARCHAR(15) NULL DEFAULT NULL,
  `Telefone` INT NULL DEFAULT NULL,
  `CPF` INT NULL DEFAULT NULL,
  `fk_tipoHospede_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Hospede_2` (`fk_tipoHospede_id` ASC) VISIBLE,
  CONSTRAINT `FK_Hospede_2`
    FOREIGN KEY (`fk_tipoHospede_id`)
    REFERENCES `dbpousada`.`tipohospede` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbpousada`.`tipoquarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpousada`.`tipoquarto` (
  `id` INT NOT NULL,
  `Descricao` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbpousada`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpousada`.`reserva` (
  `Status` VARCHAR(15) NULL DEFAULT NULL,
  `id` INT NOT NULL,
  `fk_Hospede_id` INT NULL DEFAULT NULL,
  `fk_Funcionario_id` INT NULL DEFAULT NULL,
  `fk_Hospedagem_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Reserva_2` (`fk_Hospede_id` ASC) VISIBLE,
  INDEX `FK_Reserva_3` (`fk_Funcionario_id` ASC) VISIBLE,
  INDEX `FK_Reserva_4` (`fk_Hospedagem_id` ASC) VISIBLE,
  CONSTRAINT `FK_Reserva_2`
    FOREIGN KEY (`fk_Hospede_id`)
    REFERENCES `dbpousada`.`hospede` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Reserva_3`
    FOREIGN KEY (`fk_Funcionario_id`)
    REFERENCES `dbpousada`.`funcionario` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Reserva_4`
    FOREIGN KEY (`fk_Hospedagem_id`)
    REFERENCES `dbpousada`.`hospedagem` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbpousada`.`quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpousada`.`quarto` (
  `id` INT NOT NULL,
  `NumLeitos` INT NULL DEFAULT NULL,
  `Frigobar` INT NULL DEFAULT NULL,
  `Wifi` INT NULL DEFAULT NULL,
  `Checkout` DATE NULL DEFAULT NULL,
  `Checkin` DATE NULL DEFAULT NULL,
  `Status` VARCHAR(15) NULL DEFAULT NULL,
  `fk_tipoQuarto_id` INT NULL DEFAULT NULL,
  `fk_Reserva_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Quarto_2` (`fk_tipoQuarto_id` ASC) VISIBLE,
  INDEX `FK_Quarto_3` (`fk_Reserva_id` ASC) VISIBLE,
  CONSTRAINT `FK_Quarto_2`
    FOREIGN KEY (`fk_tipoQuarto_id`)
    REFERENCES `dbpousada`.`tipoquarto` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Quarto_3`
    FOREIGN KEY (`fk_Reserva_id`)
    REFERENCES `dbpousada`.`reserva` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
